package:
  name: hansken
  version: 2024.4.17

source:
  url: https://files.pythonhosted.org/packages/e2/97/688094afddac91f6ae04482aa1fb295a731b11d9c525e9e16fe1929477ae/hansken-2024.4.17-py3-none-any.whl
  sha256: c7885f5021f3493402ba99b58036a832da73a7e08dae2e1d5946c577c50d3319

requirements:
  run:
    - requests
    - logbook
    - setuptools
    - iso8601
    - ijson
    - decorator
    - tabulate

test:
  imports:
    - hansken
