package:
  name: hansken
  version: 2022.3.1.2

source:
  url: https://files.pythonhosted.org/packages/cd/c0/574aeac703cc5068d2bd4f499c8e7010c492a339ea3c810578c475984d66/hansken-2022.6.16.tar.gz
  sha256: 0be3d85f7607791aa913e8c45ca5a045d32ff290d62ae3c47f521ddeed86cc9f

requirements:
 run:
   - requests
   - logbook
   - setuptools
   - iso8601
   - ijson
   - decorator
   - tabulate

test:
  imports:
    - hansken
