package:
  name: hansken
  version: 2022.1.21

source:
  url: https://files.pythonhosted.org/packages/df/fb/b2de05f0501dca1132c5947f2e5ec6e364ee3fba0a8f9195e9c8a0383e5d/hansken-2022.1.21.tar.gz
  sha256: e931ba119b484df990d0b0bca8a98b1e9a33a255fed617953c043f92cc4dca4d

requirements:
 run:
   - requests
   - logbook
   - setuptools
   - iso8601
   - ijson
   - decorator
   - tabulate

test:
  imports:
    - hansken
