package:
  name: hansken
  version: 2022.1.13

source:
  url: https://files.pythonhosted.org/packages/8c/37/ff972c4bb6fd5bb3e275238153f4bce7b0c6be15c1479f1d44730f944a36/hansken-2022.1.13.tar.gz
  sha256: 408e7852da8bb63fd7c3275d5bb8b55447ad68d2509f80a4b9c1c6f4968f5eee

requirements:
 run:
   - requests
   - logbook
   - setuptools
   - iso8601
   - ijson
   - decorator

test:
  imports:
    - hansken
